# Generated by Django 2.0 on 2018-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_corpus', models.CharField(max_length=200)),
                ('id_item', models.CharField(db_index=True, max_length=200)),
                ('id_item_internal', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='m_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_corpus', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('m2m_entity', models.ManyToManyField(related_name='viewer_tags', to='viewer.m_Entity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='m_entity',
            unique_together={('key_corpus', 'id_item')},
        ),
        migrations.AlterUniqueTogether(
            name='m_tag',
            unique_together={('key_corpus', 'name')},
        ),
    ]
