# Generated by Django 2.0 on 2018-02-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count_of_something', models.IntegerField(default=0)),
                ('some_boolean_value', models.BooleanField()),
                ('corpus_viewer_tags', models.ManyToManyField(related_name='corpus_viewer_items', to='viewer.m_Tag')),
            ],
        ),
    ]
